name: simple CI 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "test"
  read-hostfile:
    runs-on: ubuntu-latest
    steps:
     - name: read-hostfile
       run: cat /etc/hosts
